# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: matt.fisher@berkeley.edu
author_name: Matt Fisher
create_claude_symlink: true
create_gemini_symlink: true
has_ai_rules: true
has_binder: true
has_settings: false
kind: frontend-and-server
labextension_name: jupytercon2025-extension-workshop
project_short_description: A JupyterLab extension that displays a random image and
    caption.
python_name: jupytercon2025_extension_workshop
repository: https://github.com/jupytercon/jupytercon2025-developingextensions-demo
test: true

